### ISSUE TITLE
duc2013 data set

### ISSUE THREAD

**Issue by mikedewar** [carpedm20/neural-summary-tensorflow#1]
Is there a way to somehow get one's hands on an example data set? Or is this a problem left to the reader?

**Comment by carpedm20** [comment]
@mikedewar The reason why I tried to get DUC dataset is that the main dataset in the paper is [Annotated Gigaword corpus](https://catalog.ldc.upenn.edu/LDC2012T21) which costs $6,000. Anyway I get DUC 2013 and 2014 dataset but they only provide test set (less than 1k examples) right now.. so I don't think I can complete this project well until I get Gigaword dataset.

So, you need to prepare Gigaword corpus for run both the original code and this repo by yourself. Example of dataset can be found [here](https://github.com/carpedm20/neural-summary-tensorflow/tree/master/data/test).
