### ISSUE TITLE
What is the models package?

### ISSUE THREAD

**Issue by siddBanPsu** [carpedm20/neural-summary-tensorflow#2]
In the main.py file, it says:
`from models import NAMAS`

Cannot find that module in the code.

**Comment by carpedm20** [comment]
Hi. Sorry for late reply but I'm working on a different project right now so I don't have any plan to make some progress for this project now..

**Comment by siddBanPsu** [comment]
Sure. No problem. Thanks for letting me know.

**Comment by SeekPoint** [comment]
also see this error
